package com.narayan.abhijeet.model;

/*
 * Station codes generated using StationValuesGenerator class
 */
public enum Station {

	BLR, DHL, KOL,
	NMM,YIF,DDO,TGH,OXK,LPJ,NIJ,ZYI,KKA,NNB,UBL,DUL,NWZ,CIJ,IBC,RDN,
	QLQ,GIL,NFX,LKG,CWT,FBG,HCQ,VGW,TQJ,PUI,ZRD,IUX,UGD,UJZ,XON,NNV,
	FUW,UGB,ZRE,UGS,CYL,QOC,TTI,HVW,AVG,FIA,PAY,COP,YUK,IBZ,ENZ,JKX,
	BRP,XQF,DFI,LNA,ETJ,RJK,NIF,KJU,AAT,RXV,DPJ,RDF,YUV,PLZ,AES,EQV,
	DIP,SOZ,UFG,VCE,WVF,LZD,XFU,PGJ,QUR,DSR,YIJ,MSF,PAC,KSH,PWU,LPY,
	TBQ,SIA,NJB,NRB,ORD,NLP,FCU,FXN,QDA,BHB,SBH,XMX,ATT,LBH,TKY,NCI,
	DIX,WOJ,XZK;
	
}
